import { PrismaClient, ActivityType, ActivityCategory } from "@prisma/client";

const prisma = new PrismaClient();

interface SeedActivity {
  name: string;
  type: ActivityType;
  category: ActivityCategory;
  cost: number;
  durationMinutes: number;
  description: string;
  imageUrl?: string;
}

interface SeedCity {
  name: string;
  country: string;
  costIndex: number;
  popularity: number;
  imageUrl: string;
  activities: SeedActivity[];
}

const CITIES_DATA: SeedCity[] = [
  {
    name: "Paris",
    country: "France",
    costIndex: 1.45,
    popularity: 98,
    imageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80",
    activities: [
      {
        name: "Eiffel Tower Summit Access & Tour",
        type: ActivityType.SIGHTSEEING,
        category: ActivityCategory.ACTIVITIES,
        cost: 38.0,
        durationMinutes: 150,
        description: "Ascend to the top of the iconic Eiffel Tower with panoramic views over Paris.",
        imageUrl: "https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?w=800&q=80",
      },
      {
        name: "Louvre Museum Guided Masterpieces Walk",
        type: ActivityType.CULTURE,
        category: ActivityCategory.ACTIVITIES,
        cost: 45.0,
        durationMinutes: 180,
        description: "Skip-the-line guided exploration of the Mona Lisa, Venus de Milo, and Winged Victory.",
        imageUrl: "https://images.unsplash.com/photo-1565099824688-e93eb20fe622?w=800&q=80",
      },
      {
        name: "Traditional French Bistro Dinner in Saint-Germain",
        type: ActivityType.FOOD,
        category: ActivityCategory.MEALS,
        cost: 65.0,
        durationMinutes: 120,
        description: "Three-course culinary dinner featuring duck confit, cheese platter, and Bordeaux wine.",
        imageUrl: "https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=800&q=80",
      },
      {
        name: "Boutique Hotel Le Marais (Nightly Stay)",
        type: ActivityType.OTHER,
        category: ActivityCategory.STAY,
        cost: 180.0,
        durationMinutes: 1440,
        description: "Charming stay in historic Le Marais with private terrace and French breakfast.",
        imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80",
      },
      {
        name: "Paris Visite Metro & RER Unlimited Pass",
        type: ActivityType.OTHER,
        category: ActivityCategory.TRANSPORT,
        cost: 25.0,
        durationMinutes: 1440,
        description: "Full-day unlimited access pass across all Paris metro and transit zones.",
        imageUrl: "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800&q=80",
      },
    ],
  },
  {
    name: "Tokyo",
    country: "Japan",
    costIndex: 1.35,
    popularity: 99,
    imageUrl: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=800&q=80",
    activities: [
      {
        name: "teamLab Planets Immersive Digital Art",
        type: ActivityType.CULTURE,
        category: ActivityCategory.ACTIVITIES,
        cost: 32.0,
        durationMinutes: 120,
        description: "Walk through water and body-immersive digital flower gardens in Toyosu.",
        imageUrl: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80",
      },
      {
        name: "Shinjuku Street Food & Omoide Yokocho Tour",
        type: ActivityType.FOOD,
        category: ActivityCategory.MEALS,
        cost: 50.0,
        durationMinutes: 150,
        description: "Sample artisan yakitori, gyoza, ramen, and craft sake with a local guide.",
        imageUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&q=80",
      },
      {
        name: "Mount Fuji & Hakone Day Adventure",
        type: ActivityType.ADVENTURE,
        category: ActivityCategory.ACTIVITIES,
        cost: 95.0,
        durationMinutes: 480,
        description: "Full day excursion to Mt. Fuji 5th station and Lake Ashi pirate boat cruise.",
        imageUrl: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=800&q=80",
      },
      {
        name: "Modern Ryokan Onsen Hotel Stay (Shibuya)",
        type: ActivityType.OTHER,
        category: ActivityCategory.STAY,
        cost: 160.0,
        durationMinutes: 1440,
        description: "Peaceful Japanese tatami suite with hot spring bath in central Tokyo.",
        imageUrl: "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&q=80",
      },
      {
        name: "Tokyo Subway 72-Hour Tourist Pass",
        type: ActivityType.OTHER,
        category: ActivityCategory.TRANSPORT,
        cost: 12.0,
        durationMinutes: 4320,
        description: "Unlimited rides on all Tokyo Metro and Toei Subway lines for 3 days.",
        imageUrl: "https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=800&q=80",
      },
    ],
  },
  {
    name: "Rome",
    country: "Italy",
    costIndex: 1.25,
    popularity: 96,
    imageUrl: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&q=80",
    activities: [
      {
        name: "Colosseum Arena Floor & Roman Forum VIP Tour",
        type: ActivityType.CULTURE,
        category: ActivityCategory.ACTIVITIES,
        cost: 55.0,
        durationMinutes: 180,
        description: "Walk onto the gladiator arena floor and discover ancient Roman ruins.",
        imageUrl: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&q=80",
      },
      {
        name: "Trastevere Evening Food & Wine Stroll",
        type: ActivityType.FOOD,
        category: ActivityCategory.MEALS,
        cost: 60.0,
        durationMinutes: 180,
        description: "Authentic cacio e pepe, supplì, artisan gelato, and regional Italian wines.",
        imageUrl: "https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800&q=80",
      },
      {
        name: "Vespa City Highlights Riding Tour",
        type: ActivityType.ADVENTURE,
        category: ActivityCategory.ACTIVITIES,
        cost: 85.0,
        durationMinutes: 210,
        description: "Zip past the Pantheon, Trevi Fountain, and Spanish Steps on a vintage Vespa.",
        imageUrl: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800&q=80",
      },
      {
        name: "Historic Piazza Navona Suite (Nightly Stay)",
        type: ActivityType.OTHER,
        category: ActivityCategory.STAY,
        cost: 140.0,
        durationMinutes: 1440,
        description: "Elegant boutique apartment steps from Piazza Navona and Pantheon.",
        imageUrl: "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80",
      },
      {
        name: "Roma Pass 48-Hour Transit & Museum Pass",
        type: ActivityType.OTHER,
        category: ActivityCategory.TRANSPORT,
        cost: 32.0,
        durationMinutes: 2880,
        description: "Free public transit and included entry to Roman cultural sites.",
        imageUrl: "https://images.unsplash.com/photo-1520175480921-4edfa2983e0f?w=800&q=80",
      },
    ],
  },
  {
    name: "New York",
    country: "United States",
    costIndex: 1.8,
    popularity: 97,
    imageUrl: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&q=80",
    activities: [
      {
        name: "Empire State Building 86th Floor Observatory",
        type: ActivityType.SIGHTSEEING,
        category: ActivityCategory.ACTIVITIES,
        cost: 44.0,
        durationMinutes: 120,
        description: "Legendary 360-degree open-air views of Manhattan skyline.",
        imageUrl: "https://images.unsplash.com/photo-1506146332389-18140dc7b2fb?w=800&q=80",
      },
      {
        name: "Chelsea Market & High Line Food Tour",
        type: ActivityType.FOOD,
        category: ActivityCategory.MEALS,
        cost: 75.0,
        durationMinutes: 150,
        description: "Taste lobster rolls, artisanal tacos, and artisanal babka while walking the elevated park.",
        imageUrl: "https://images.unsplash.com/photo-1534430480872-3498386e7856?w=800&q=80",
      },
      {
        name: "Central Park Bike Rental & Adventure Loop",
        type: ActivityType.ADVENTURE,
        category: ActivityCategory.ACTIVITIES,
        cost: 25.0,
        durationMinutes: 180,
        description: "Cycle through Central Park loop, Bethesda Terrace, and Strawberry Fields.",
        imageUrl: "https://images.unsplash.com/photo-1538688525198-9b88f6f53126?w=800&q=80",
      },
      {
        name: "Midtown Manhattan Loft Hotel (Nightly Stay)",
        type: ActivityType.OTHER,
        category: ActivityCategory.STAY,
        cost: 250.0,
        durationMinutes: 1440,
        description: "Modern hotel stay with city views near Times Square and Broadway.",
        imageUrl: "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&q=80",
      },
      {
        name: "7-Day Unlimited MTA MetroCard",
        type: ActivityType.OTHER,
        category: ActivityCategory.TRANSPORT,
        cost: 34.0,
        durationMinutes: 10080,
        description: "Unlimited subway and local bus transportation throughout NYC.",
        imageUrl: "https://images.unsplash.com/photo-1518391846015-55a9cc003b25?w=800&q=80",
      },
    ],
  },
  {
    name: "Barcelona",
    country: "Spain",
    costIndex: 1.15,
    popularity: 94,
    imageUrl: "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800&q=80",
    activities: [
      {
        name: "Sagrada Família Fast-Track Tower Tour",
        type: ActivityType.CULTURE,
        category: ActivityCategory.ACTIVITIES,
        cost: 40.0,
        durationMinutes: 120,
        description: "Gaudí’s crowning masterpiece with towering stained-glass views.",
        imageUrl: "https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800&q=80",
      },
      {
        name: "Gothic Quarter Tapas & Sangria Night",
        type: ActivityType.FOOD,
        category: ActivityCategory.MEALS,
        cost: 45.0,
        durationMinutes: 150,
        description: "Patatas bravas, jamón ibérico, and crisp cava in medieval alleyways.",
        imageUrl: "https://images.unsplash.com/photo-1515443961218-a51367888e4b?w=800&q=80",
      },
      {
        name: "Barceloneta Beach Paddleboarding Adventure",
        type: ActivityType.ADVENTURE,
        category: ActivityCategory.ACTIVITIES,
        cost: 30.0,
        durationMinutes: 90,
        description: "Paddle along the Mediterranean coast with views of the W Hotel skyline.",
        imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
      },
      {
        name: "Eixample Modernist Boutique Hotel",
        type: ActivityType.OTHER,
        category: ActivityCategory.STAY,
        cost: 130.0,
        durationMinutes: 1440,
        description: "Stylish room with rooftop swimming pool and cocktail bar.",
        imageUrl: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80",
      },
      {
        name: "Hola Barcelona 48-Hour Travel Card",
        type: ActivityType.OTHER,
        category: ActivityCategory.TRANSPORT,
        cost: 17.5,
        durationMinutes: 2880,
        description: "Unlimited rides on Barcelona metro, tram, buses, and airport train.",
        imageUrl: "https://images.unsplash.com/photo-1511527661048-7fe73d85e9a4?w=800&q=80",
      },
    ],
  },
  {
    name: "London",
    country: "United Kingdom",
    costIndex: 1.6,
    popularity: 97,
    imageUrl: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&q=80",
    activities: [
      {
        name: "Tower of London & Crown Jewels Tour",
        type: ActivityType.CULTURE,
        category: ActivityCategory.ACTIVITIES,
        cost: 35.0,
        durationMinutes: 150,
        description: "Discover 1,000 years of royal history and the priceless Crown Jewels.",
        imageUrl: "https://images.unsplash.com/photo-1526129318478-62ed807ebdf9?w=800&q=80",
      },
      {
        name: "Traditional Afternoon Tea at Covent Garden",
        type: ActivityType.FOOD,
        category: ActivityCategory.MEALS,
        cost: 55.0,
        durationMinutes: 120,
        description: "Tiered clotted cream scones, finger sandwiches, and premium English teas.",
        imageUrl: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&q=80",
      },
      {
        name: "Thames River High-Speed RIB Speedboat Ride",
        type: ActivityType.ADVENTURE,
        category: ActivityCategory.ACTIVITIES,
        cost: 50.0,
        durationMinutes: 60,
        description: "Fast-paced adrenaline thrill past Tower Bridge and Canary Wharf.",
        imageUrl: "https://images.unsplash.com/photo-1486299267070-83823f5448dd?w=800&q=80",
      },
      {
        name: "Bloomsbury Boutique Townhouse (Nightly Stay)",
        type: ActivityType.OTHER,
        category: ActivityCategory.STAY,
        cost: 210.0,
        durationMinutes: 1440,
        description: "Victorian design hotel near the British Museum and Soho.",
        imageUrl: "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800&q=80",
      },
      {
        name: "London Oyster Transit Card Credit",
        type: ActivityType.OTHER,
        category: ActivityCategory.TRANSPORT,
        cost: 20.0,
        durationMinutes: 1440,
        description: "Preloaded contactless transit for London Underground and red double-decker buses.",
        imageUrl: "https://images.unsplash.com/photo-1520986606214-8b456906c813?w=800&q=80",
      },
    ],
  },
  {
    name: "Kyoto",
    country: "Japan",
    costIndex: 1.1,
    popularity: 92,
    imageUrl: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80",
    activities: [
      {
        name: "Fushimi Inari Shrine & 10,000 Torii Gates Walk",
        type: ActivityType.SIGHTSEEING,
        category: ActivityCategory.ACTIVITIES,
        cost: 15.0,
        durationMinutes: 180,
        description: "Hike through thousands of vermilion shrine gates on sacred Mount Inari.",
        imageUrl: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80",
      },
      {
        name: "Traditional Tea Ceremony & Matcha Workshop",
        type: ActivityType.CULTURE,
        category: ActivityCategory.ACTIVITIES,
        cost: 35.0,
        durationMinutes: 90,
        description: "Master the zen art of green tea preparation in a 200-year-old teahouse.",
        imageUrl: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=800&q=80",
      },
      {
        name: "Kaiseki Multi-Course Ryotei Dinner",
        type: ActivityType.FOOD,
        category: ActivityCategory.MEALS,
        cost: 80.0,
        durationMinutes: 150,
        description: "Exquisite seasonal dishes presented with artistic precision in Gion.",
        imageUrl: "https://images.unsplash.com/photo-1553621042-f6e147245754?w=800&q=80",
      },
      {
        name: "Traditional Machiya Heritage House Stay",
        type: ActivityType.OTHER,
        category: ActivityCategory.STAY,
        cost: 140.0,
        durationMinutes: 1440,
        description: "Private wooden townhouse with Japanese garden and cedar wood bath.",
        imageUrl: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=800&q=80",
      },
      {
        name: "Kyoto City Bus & Subway 1-Day Pass",
        type: ActivityType.OTHER,
        category: ActivityCategory.TRANSPORT,
        cost: 9.0,
        durationMinutes: 1440,
        description: "Seamless transit between Kinkaku-ji, Arashiyama, and Gion districts.",
        imageUrl: "https://images.unsplash.com/photo-1492571350019-22de08371fd3?w=800&q=80",
      },
    ],
  },
  {
    name: "Dubai",
    country: "United Arab Emirates",
    costIndex: 1.5,
    popularity: 95,
    imageUrl: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80",
    activities: [
      {
        name: "Burj Khalifa 124th & 125th Floor Observation Deck",
        type: ActivityType.SIGHTSEEING,
        category: ActivityCategory.ACTIVITIES,
        cost: 50.0,
        durationMinutes: 90,
        description: "Stand atop the world's tallest skyscraper with breathtaking Arabian Gulf views.",
        imageUrl: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80",
      },
      {
        name: "Red Dunes Desert Safari & BBQ Camp",
        type: ActivityType.ADVENTURE,
        category: ActivityCategory.ACTIVITIES,
        cost: 65.0,
        durationMinutes: 360,
        description: "Dune bashing in 4x4s, sandboarding, camel rides, and belly dance dinner show.",
        imageUrl: "https://images.unsplash.com/photo-1451337516015-6b6e9a44a8a3?w=800&q=80",
      },
      {
        name: "Marina Yacht Cruise Dinner Experience",
        type: ActivityType.FOOD,
        category: ActivityCategory.MEALS,
        cost: 70.0,
        durationMinutes: 120,
        description: "International buffet dinner while cruising Dubai Marina illuminated skyscrapers.",
        imageUrl: "https://images.unsplash.com/photo-1580674684081-7617fbf3d745?w=800&q=80",
      },
      {
        name: "Downtown Luxury Hotel Suite (Nightly Stay)",
        type: ActivityType.OTHER,
        category: ActivityCategory.STAY,
        cost: 220.0,
        durationMinutes: 1440,
        description: "Lavish 5-star hotel with infinity pool overlooking the Dubai Fountain.",
        imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80",
      },
      {
        name: "Dubai Nol Red Transit Ticket",
        type: ActivityType.OTHER,
        category: ActivityCategory.TRANSPORT,
        cost: 8.0,
        durationMinutes: 1440,
        description: "Direct access to the automated driverless Dubai Metro and tram lines.",
        imageUrl: "https://images.unsplash.com/photo-1526495124232-a04e1849168c?w=800&q=80",
      },
    ],
  },
  {
    name: "Bangkok",
    country: "Thailand",
    costIndex: 0.7,
    popularity: 93,
    imageUrl: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800&q=80",
    activities: [
      {
        name: "Grand Palace & Wat Phra Kaew Temple Tour",
        type: ActivityType.CULTURE,
        category: ActivityCategory.ACTIVITIES,
        cost: 20.0,
        durationMinutes: 150,
        description: "Marvel at golden stupas and the sacred Emerald Buddha temple.",
        imageUrl: "https://images.unsplash.com/photo-1563492065599-3520f775eeed?w=800&q=80",
      },
      {
        name: "Chinatown Yaowarat Midnight Tuk-Tuk Food Trail",
        type: ActivityType.FOOD,
        category: ActivityCategory.MEALS,
        cost: 30.0,
        durationMinutes: 180,
        description: "Pad thai, crispy pork belly, mango sticky rice, and dim sum stalls.",
        imageUrl: "https://images.unsplash.com/photo-1552611052-33e04de081de?w=800&q=80",
      },
      {
        name: "Damnoen Saduak Floating Market Longtail Boat",
        type: ActivityType.ADVENTURE,
        category: ActivityCategory.ACTIVITIES,
        cost: 35.0,
        durationMinutes: 300,
        description: "Navigate canals packed with wooden boats selling tropical fruits and noodles.",
        imageUrl: "https://images.unsplash.com/photo-1528181304800-259b08848526?w=800&q=80",
      },
      {
        name: "Riverside Resort with Tropical Pool (Nightly Stay)",
        type: ActivityType.OTHER,
        category: ActivityCategory.STAY,
        cost: 75.0,
        durationMinutes: 1440,
        description: "Scenic stay on the Chao Phraya River with river shuttle service.",
        imageUrl: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80",
      },
      {
        name: "BTS Skytrain 1-Day Unlimited Pass",
        type: ActivityType.OTHER,
        category: ActivityCategory.TRANSPORT,
        cost: 5.0,
        durationMinutes: 1440,
        description: "Air-conditioned elevated transit connecting Sukhumvit and Siam.",
        imageUrl: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800&q=80",
      },
    ],
  },
  {
    name: "Amsterdam",
    country: "Netherlands",
    costIndex: 1.4,
    popularity: 91,
    imageUrl: "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800&q=80",
    activities: [
      {
        name: "Van Gogh Museum & Rijksmuseum Guided Tour",
        type: ActivityType.CULTURE,
        category: ActivityCategory.ACTIVITIES,
        cost: 48.0,
        durationMinutes: 180,
        description: "Admire Sunflowers, Almond Blossoms, and Rembrandt’s Night Watch.",
        imageUrl: "https://images.unsplash.com/photo-1584003564911-a7a321c84e1c?w=800&q=80",
      },
      {
        name: "Canal Evening Cruise with Dutch Cheese & Wine",
        type: ActivityType.FOOD,
        category: ActivityCategory.MEALS,
        cost: 42.0,
        durationMinutes: 90,
        description: "Glide through UNESCO canal belt with artisan Gouda and fine wines.",
        imageUrl: "https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?w=800&q=80",
      },
      {
        name: "Zaanse Schans Windmills & Countryside Bike Tour",
        type: ActivityType.ADVENTURE,
        category: ActivityCategory.ACTIVITIES,
        cost: 50.0,
        durationMinutes: 240,
        description: "Cycle past historic windmills, clog workshops, and cheese farms.",
        imageUrl: "https://images.unsplash.com/photo-1509356843151-3e7d96241e11?w=800&q=80",
      },
      {
        name: "Herengracht Canal House Stay (Nightly Stay)",
        type: ActivityType.OTHER,
        category: ActivityCategory.STAY,
        cost: 175.0,
        durationMinutes: 1440,
        description: "17th-century canal house boutique hotel in Jordaan district.",
        imageUrl: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80",
      },
      {
        name: "GVB Amsterdam 48-Hour Tram & Metro Pass",
        type: ActivityType.OTHER,
        category: ActivityCategory.TRANSPORT,
        cost: 16.0,
        durationMinutes: 2880,
        description: "Unlimited rides on all GVB trams, buses, and ferries.",
        imageUrl: "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800&q=80",
      },
    ],
  },
  {
    name: "Singapore",
    country: "Singapore",
    costIndex: 1.5,
    popularity: 94,
    imageUrl: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&q=80",
    activities: [
      {
        name: "Gardens by the Bay Flower Dome & Cloud Forest",
        type: ActivityType.SIGHTSEEING,
        category: ActivityCategory.ACTIVITIES,
        cost: 38.0,
        durationMinutes: 150,
        description: "Explore the giant glass biodomes and walk along the Supertree Grove.",
        imageUrl: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&q=80",
      },
      {
        name: "Lau Pa Sat Hawker Center Feast",
        type: ActivityType.FOOD,
        category: ActivityCategory.MEALS,
        cost: 25.0,
        durationMinutes: 90,
        description: "Smoky chicken satay with peanut sauce, Hainanese chicken rice, and laksa.",
        imageUrl: "https://images.unsplash.com/photo-1567337710282-00832b415979?w=800&q=80",
      },
      {
        name: "Sentosa Island Mega Adventure Zipline",
        type: ActivityType.ADVENTURE,
        category: ActivityCategory.ACTIVITIES,
        cost: 45.0,
        durationMinutes: 120,
        description: "High-speed 450m zipline over jungle canopies landing onto Siloso Beach.",
        imageUrl: "https://images.unsplash.com/photo-1506354666786-959d6d497f1a?w=800&q=80",
      },
      {
        name: "Marina Bay View Heritage Hotel Stay",
        type: ActivityType.OTHER,
        category: ActivityCategory.STAY,
        cost: 240.0,
        durationMinutes: 1440,
        description: "Luxurious stay with infinity pool overlooking the Singapore skyline.",
        imageUrl: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&q=80",
      },
      {
        name: "Singapore Tourist Pass Plus 2-Day Card",
        type: ActivityType.OTHER,
        category: ActivityCategory.TRANSPORT,
        cost: 22.0,
        durationMinutes: 2880,
        description: "Unlimited travel on MRT trains and city buses.",
        imageUrl: "https://images.unsplash.com/photo-1508963493744-76fce69379c0?w=800&q=80",
      },
    ],
  },
  {
    name: "Cairo",
    country: "Egypt",
    costIndex: 0.6,
    popularity: 88,
    imageUrl: "https://images.unsplash.com/photo-1572252009286-268acec5ca0a?w=800&q=80",
    activities: [
      {
        name: "Giza Pyramids & Great Sphinx Private Guide",
        type: ActivityType.CULTURE,
        category: ActivityCategory.ACTIVITIES,
        cost: 40.0,
        durationMinutes: 240,
        description: "Stand before the last remaining Ancient Wonder of the World.",
        imageUrl: "https://images.unsplash.com/photo-1572252009286-268acec5ca0a?w=800&q=80",
      },
      {
        name: "Khan el-Khalili Bazaar Walking & Street Food Tour",
        type: ActivityType.FOOD,
        category: ActivityCategory.MEALS,
        cost: 20.0,
        durationMinutes: 150,
        description: "Savor authentic koshary, falafel, and sweet mint tea in historic Cairo.",
        imageUrl: "https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=800&q=80",
      },
      {
        name: "Quad Biking Safari on the Giza Desert Sands",
        type: ActivityType.ADVENTURE,
        category: ActivityCategory.ACTIVITIES,
        cost: 35.0,
        durationMinutes: 120,
        description: "Race ATVs across golden desert dunes with pyramids in the backdrop.",
        imageUrl: "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=800&q=80",
      },
      {
        name: "Nile River View Boutique Hotel (Nightly Stay)",
        type: ActivityType.OTHER,
        category: ActivityCategory.STAY,
        cost: 65.0,
        durationMinutes: 1440,
        description: "Balcony room looking out directly over the tranquil River Nile.",
        imageUrl: "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80",
      },
      {
        name: "Cairo Private Chauffeur & Day Transit",
        type: ActivityType.OTHER,
        category: ActivityCategory.TRANSPORT,
        cost: 25.0,
        durationMinutes: 480,
        description: "Dedicated private air-conditioned vehicle for effortless city transit.",
        imageUrl: "https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=800&q=80",
      },
    ],
  },
  {
    name: "Sydney",
    country: "Australia",
    costIndex: 1.55,
    popularity: 93,
    imageUrl: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800&q=80",
    activities: [
      {
        name: "Sydney Opera House Architectural Tour",
        type: ActivityType.CULTURE,
        category: ActivityCategory.ACTIVITIES,
        cost: 35.0,
        durationMinutes: 90,
        description: "Step inside the world-famous sails and learn about its design triumphs.",
        imageUrl: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800&q=80",
      },
      {
        name: "Sydney Harbour Seafood Dinner Cruise",
        type: ActivityType.FOOD,
        category: ActivityCategory.MEALS,
        cost: 75.0,
        durationMinutes: 150,
        description: "Fresh Barramundi and Sydney rock oysters under illuminated Harbour Bridge.",
        imageUrl: "https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?w=800&q=80",
      },
      {
        name: "Bondi to Coogee Coastal Cliff Walk & Surf Lesson",
        type: ActivityType.ADVENTURE,
        category: ActivityCategory.ACTIVITIES,
        cost: 55.0,
        durationMinutes: 210,
        description: "Catch your first wave at Bondi followed by breathtaking coastal cliff paths.",
        imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
      },
      {
        name: "Circular Quay Waterside Hotel (Nightly Stay)",
        type: ActivityType.OTHER,
        category: ActivityCategory.STAY,
        cost: 210.0,
        durationMinutes: 1440,
        description: "Harbour views with easy ferry connections to Manly and Taronga Zoo.",
        imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80",
      },
      {
        name: "Sydney Opal Card Transit Pass",
        type: ActivityType.OTHER,
        category: ActivityCategory.TRANSPORT,
        cost: 18.0,
        durationMinutes: 1440,
        description: "Seamless travel on Sydney trains, light rail, and iconic harbour ferries.",
        imageUrl: "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800&q=80",
      },
    ],
  },
  {
    name: "Rio de Janeiro",
    country: "Brazil",
    costIndex: 0.9,
    popularity: 89,
    imageUrl: "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800&q=80",
    activities: [
      {
        name: "Christ the Redeemer & Corcovado Train",
        type: ActivityType.SIGHTSEEING,
        category: ActivityCategory.ACTIVITIES,
        cost: 30.0,
        durationMinutes: 150,
        description: "Cogwheel train through Tijuca Rainforest to the statue overlooking Rio.",
        imageUrl: "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800&q=80",
      },
      {
        name: "Copacabana Beachfront Churrascaria BBQ Feast",
        type: ActivityType.FOOD,
        category: ActivityCategory.MEALS,
        cost: 40.0,
        durationMinutes: 120,
        description: "Endless Brazilian rodízio meats, feijoada, and fresh lime caipirinhas.",
        imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80",
      },
      {
        name: "Sugarloaf Mountain Cable Car & Sunset",
        type: ActivityType.ADVENTURE,
        category: ActivityCategory.ACTIVITIES,
        cost: 32.0,
        durationMinutes: 150,
        description: "360-degree glass cable car ride with panoramic sunset views over Guanabara Bay.",
        imageUrl: "https://images.unsplash.com/photo-1516306580123-e6e52b1b7b5f?w=800&q=80",
      },
      {
        name: "Ipanema Beach Boutique Suite (Nightly Stay)",
        type: ActivityType.OTHER,
        category: ActivityCategory.STAY,
        cost: 110.0,
        durationMinutes: 1440,
        description: "Oceanfront hotel with rooftop terrace in the heart of Ipanema.",
        imageUrl: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80",
      },
      {
        name: "Rio Metrô & VLT Light Rail Pass",
        type: ActivityType.OTHER,
        category: ActivityCategory.TRANSPORT,
        cost: 8.0,
        durationMinutes: 1440,
        description: "Safe and swift transit connecting Centro, Copacabana, and Ipanema.",
        imageUrl: "https://images.unsplash.com/photo-1518391846015-55a9cc003b25?w=800&q=80",
      },
    ],
  },
  {
    name: "Istanbul",
    country: "Turkey",
    costIndex: 0.85,
    popularity: 92,
    imageUrl: "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800&q=80",
    activities: [
      {
        name: "Hagia Sophia & Blue Mosque Guided Tour",
        type: ActivityType.CULTURE,
        category: ActivityCategory.ACTIVITIES,
        cost: 25.0,
        durationMinutes: 150,
        description: "Marvel at ancient Byzantine mosaics and magnificent Ottoman dome architecture.",
        imageUrl: "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800&q=80",
      },
      {
        name: "Bosphorus Sunset Yacht Cruise & Turkish Meze",
        type: ActivityType.FOOD,
        category: ActivityCategory.MEALS,
        cost: 35.0,
        durationMinutes: 120,
        description: "Cruise between Europe and Asia sipping Turkish tea and baklava.",
        imageUrl: "https://images.unsplash.com/photo-1541432901042-2d8bd64b4a1b?w=800&q=80",
      },
      {
        name: "Grand Bazaar & Spice Market Treasure Hunt",
        type: ActivityType.ADVENTURE,
        category: ActivityCategory.ACTIVITIES,
        cost: 20.0,
        durationMinutes: 180,
        description: "Explore 4,000 vibrant shops filled with lanterns, spices, and silk rugs.",
        imageUrl: "https://images.unsplash.com/photo-1527838832700-5059252407fa?w=800&q=80",
      },
      {
        name: "Sultanahmet Heritage Mansion Stay (Nightly Stay)",
        type: ActivityType.OTHER,
        category: ActivityCategory.STAY,
        cost: 90.0,
        durationMinutes: 1440,
        description: "Restored Ottoman mansion located within walking distance of Topkapi Palace.",
        imageUrl: "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80",
      },
      {
        name: "Istanbulkart Public Transit Card",
        type: ActivityType.OTHER,
        category: ActivityCategory.TRANSPORT,
        cost: 7.0,
        durationMinutes: 1440,
        description: "Universal card for historic trams, metro, funiculars, and Bosphorus ferries.",
        imageUrl: "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800&q=80",
      },
    ],
  },
];

export async function seedDatabase() {
  console.log("🌱 Starting GlobeTrotter database seed...");

  // Clear existing activities and cities safely if needed
  await prisma.sectionActivity.deleteMany();
  await prisma.section.deleteMany();
  await prisma.trip.deleteMany();
  await prisma.activity.deleteMany();
  await prisma.city.deleteMany();

  console.log("Cleared old cities/activities/trips.");

  let cityCount = 0;
  let activityCount = 0;

  for (const cityData of CITIES_DATA) {
    const { activities, ...cityFields } = cityData;

    const city = await prisma.city.create({
      data: cityFields,
    });
    cityCount++;

    for (const act of activities) {
      await prisma.activity.create({
        data: {
          cityId: city.id,
          name: act.name,
          type: act.type,
          category: act.category,
          cost: act.cost,
          durationMinutes: act.durationMinutes,
          description: act.description,
          imageUrl: act.imageUrl,
        },
      });
      activityCount++;
    }
  }

  console.log(`✅ Successfully seeded ${cityCount} cities and ${activityCount} activities.`);
}

if (require.main === module) {
  seedDatabase()
    .catch((err) => {
      console.error("❌ Seed error:", err);
      process.exit(1);
    })
    .finally(async () => {
      await prisma.$disconnect();
    });
}
